apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls-cert
  namespace: default
spec:
  commonName: ingress
  dnsNames:
  - '*.h2o-2-18171.h2o.vmware.com'
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ingress-ca-issuer
  renewBefore: 360h0m0s
  secretName: ingress-tls
  usages:
  - server auth
  - client auth
