#@data/values
---
routing:
  namespace: enterprise-routing
  host: ingress.h2o-2-18171.h2o.vmware.com
  tlsSecret: ""
  routes:
  - name: harbor
    type: external
    namespace: enterprise-routing
    service: harbor
    port: 80
    path: /harbor
    hostname: harbor.ingress.h2o-2-18171.h2o.vmware.com
    no_replacement: true
  - name: nginx
    type: internal
    namespace: nginx
    service: my-nginx
    port: 80
    path: /nginx
  - name: kuard
    type: internal
    namespace: kuard
    service: kuard-service
    port: 80
    path: /kuard




